# This workflow will  requests and apply a label based on the
# paths that are modified in the pull request.

name: Spring Data GitHub Issues

on:
  issues:
    types: [opened, edited, reopened, closed]
  issue_comment:
    types: [created]    
  pull_request:
    types: [opened, edited, reopened]

jobs:
  Inbox:
    runs-on: ubuntu-latest
    if: (github.event.action == 'opened' || github.event.action == 'reopened') && github.event.pull_request == null && !contains(join(github.event.issue.labels.*.name, ', '), 'dependency-upgrade')
    steps:
      - name: Create or Update Issue Card
        uses: peter-evans/create-or-update-project-card@v1.1.2
        with:
          project-name: 'Ticket Playground'
          column-name: 'Inbox'
          project-location: 'sampledump'
          token: ${{ secrets.GH_TOKEN }}
  Done:
    runs-on: ubuntu-latest
    if: (github.event.action == 'closed') && github.event.pull_request == null
    steps:
      - name: Update Issue Card
        uses: peter-evans/create-or-update-project-card@v1.1.2
        with:
          project-name: 'Ticket Playground'
          column-name: 'Done'
          project-location: 'sampledump'
          token: ${{ secrets.GH_TOKEN }}
  Pull-Request:
    runs-on: ubuntu-latest
    if: (github.event.action == 'opened' || github.event.action == 'reopened') && github.event.pull_request != null
    steps:
      - name: Create or Update Issue Card
        uses: peter-evans/create-or-update-project-card@v1.1.2
        with:
          project-name: 'Ticket Playground'
          column-name: 'Review pending'
          project-location: 'sampledump'
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GH_TOKEN }}
  Feedback-Provided:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'spring-projects' && github.event.action == 'created' && contains(join(github.event.issue.labels.*.name, ', '), 'waiting-for-feedback')
    steps:
      - name: Update Project Card
        uses: peter-evans/create-or-update-project-card@v1.1.2
        with:
          project-name: 'Spring Data'
          column-name: 'Feedback provided'
          project-location: 'spring-projects'
          token: ${{ secrets.GH_TOKEN }}
