# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler

on:
  issues:
    types: [opened, edited, reopened]
  issue_comment:
    types: [created]    
  pull_request:
    types: [opened, edited, reopened]


jobs:
  Inbox:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'opened' || github.event.action == 'reopened' }}
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: 'Ticket Playground'
          column-name: 'Inbox'
          project-location: 'sampledump'
          token: ${{ secrets.GH_TOKEN }}
  Feedback-Provided:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'created' && (contains(github.event.issue.labels.*.name, 'status: waiting-for-feedback') || contains(github.event.issue.labels.*.name, 'status: feedback-provided')) }}
    steps:
      - name: Update Project Card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: 'Ticket Playground'
          column-name: 'Feedback provided'
          project-location: 'sampledump'
          token: ${{ secrets.GH_TOKEN }}


